### ISSUE TITLE
How to reset

### ISSUE THREAD

**Issue by luiselizondo** [AprilBrother/AButton#1]
I set the wrong configuration, how do I reset the button? I tried disabling the network so it sets the Wifi again after it fails to connect but with no success.

**Comment by volca** [comment]
Please hold the button about 10~ seconds until you see the LED blinks.

Have you configured the wifi?

**Comment by luiselizondo** [comment]
I did configure the wifi. Reading at the code I found that that I probably wasn't turning of my wifi long enough so I completely shut down my router and waited until the button created the wifi again. It took about 2 minutes. Anyway, thanks for the help. If you can elaborate how to reset it would be great in case I need to do it again.  

Luis Elizondo

**Comment by volca** [comment]
There's no a straight way to reset the button. Do you want to clean the WiFi configuration? 

Does "re-configure a wrong SSID and password" resolve the problem?

**Comment by luiselizondo** [comment]
I configured the IFTTT token with the wrong token and I wanted to changed it. In the end I solved it by turning of the router so the button tried 10 times to connect and then it started it's own Wifi network. Thanks.
